server:
  port: 8083

spring:
  application:
    name: logistics-service
  datasource:
    url: jdbc:mysql://localhost:3306/logistics_db?createDatabaseIfNotExist=true
    username: root
    password: root

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html